#!/bin/bash
if [ -z $1 ]; then
    echo "Parameter #1: must be either HB, HBL, HBLO";
fi
relation="Homer-Bart"
classes="Homer, Bart"
features="orange blanc gris vert bleu"
if [[ $1 == "HBL" ]];then
    relation="Homer-Bart-Lisa"
    classes="Homer, Bart, Lisa"
    features="orange blanc gris vert bleu rouge"
elif [[ $1 == "HBLO" ]];then
    relation="Homer-Bart-Lisa"
    classes="Homer, Bart, Lisa, Others"
    features="orange blanc gris vert bleu rouge"
fi

header="@relation $relation\n"
for feature in $features ; do header="$header@attribute primitive_$feature numeric\n"; done

header="$header@attribute classe {$classes}\n@data\n"

echo $header

echo -e "$header$(cat EquipeI-Apprentissage-$1.txt)" > EquipeI-Apprentissage-$1.arff
echo -e "$header$(cat EquipeI-Validation-$1.txt)" > EquipeI-Validation-$1.arff
