#!/bin/bash

echo -e "@relation Homer-Bart\n@attribute primitive1 numeric\n@attribute primitive2 numeric\n@attribute primitive3 numeric\n@attribute primitive4 numeric\n@attribute primitive5 numeric\n@attribute classe {Homer, Bart}\n@data\n$(cat apprentissage-homer-bart.txt)" > apprentissage-homer-bart.arff
